### ISSUE TITLE
Example for execa environment does not work

### ISSUE THREAD

**Issue by Konard** [link-foundation/use-m#2]
```
konard@MacBook-Pro-Konstantin execa-test % node example.mjs 
lodash@latest installed successfully.
undefined:150
    throw new Error(`Failed to import module from '${modulePath}'.`, { cause: error });
          ^

Error: Failed to import module from '/Users/konard/.nvm/versions/node/v20.17.0/lib/node_modules/lodash-vlatest'.
    at baseUse (eval at <anonymous> (file:///Users/konard/Desktop/use-m-tests/execa-test/example.mjs:3:17), <anonymous>:150:11)
    at async file:///Users/konard/Desktop/use-m-tests/execa-test/example.mjs:5:11 {
  [cause]: Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/Users/konard/.nvm/versions/node/v20.17.0/lib/node_modules/lodash-vlatest' is not supported resolving ES modules imported from /Users/konard/Desktop/use-m-tests/execa-test/example.mjs
  Did you mean to import "/Users/konard/.nvm/versions/node/v20.17.0/lib/node_modules/lodash-vlatest/lodash.js"?
      at finalizeResolution (node:internal/modules/esm/resolve:259:11)
      at moduleResolve (node:internal/modules/esm/resolve:933:10)
      at defaultResolve (node:internal/modules/esm/resolve:1169:11)
      at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:540:12)
      at ModuleLoader.resolve (node:internal/modules/esm/loader:509:25)
      at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:239:38)
      at ModuleLoader.import (node:internal/modules/esm/loader:472:34)
      at defaultImportModuleDynamicallyForModule (node:internal/modules/esm/utils:214:31)
      at importModuleDynamicallyCallback (node:internal/modules/esm/utils:253:12)
      at baseUse (eval at <anonymous> (file:///Users/konard/Desktop/use-m-tests/execa-test/example.mjs:3:17), <anonymous>:142:20) {
    code: 'ERR_UNSUPPORTED_DIR_IMPORT',
    url: 'file:///Users/konard/.nvm/versions/node/v20.17.0/lib/node_modules/lodash-vlatest'
  }
}

Node.js v20.17.0
```

**Comment by Konard** [comment]
# Solution

Add metaUrl option:

```
   metaUrl: import.meta.url,
```

Like this:

```js
  const use = await fetch('https://unpkg.com/use-m@3.3.1/src/use.js')
    .then(response => response.text())
    .then(code => eval(code)({
      metaUrl: import.meta.url,
    }));

  const _ = await use('lodash@latest');
  const { $: $$ } = await use('execa@latest');
  const $ = $$({ verbose: 'full' });

  const { stdout } = await $`ls`.pipe`grep js`;
  const files = _.filter(_.split(stdout, '\n'), (item) => !_.isEmpty(item));
  console.log(files);
```
